version: 2
updates:
# GitHub Actions dependencies (actions/checkout, actions/cache, etc.)
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
   interval: "weekly"
   day: "monday"
  open-pull-requests-limit: 5
  labels:
    - "dependencies"
    - "actions"
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
    - "dependencies"
    - "maven"
