(module $bytecoder
    (type $t0 (func (param i32) (result i32)))
    (type $runtimetype (struct (field $vt_resolver (ref $t0))))
    (type $java$lang$Object (struct (field $runtimetype (ref $runtimetype))))
    (type $java$nio$charset$CodingErrorAction (struct_subtype (field $runtimetype (ref $runtimetype)) (field $name (ref $java$lang$Object)) $java$lang$Object))
    (type $java$nio$ByteOrder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $name (ref $java$lang$Object)) $java$lang$Object))
    (type $java$nio$charset$CoderResult (struct_subtype (field $runtimetype (ref $runtimetype)) (field $type i32) (field $length i32) $java$lang$Object))
    (type $jdk$internal$util$ArraysSupport (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$nio$charset$CoderResult$Cache (struct_subtype (field $runtimetype (ref $runtimetype)) (field $unmappable (ref $java$lang$Object)) (field $malformed (ref $java$lang$Object)) $java$lang$Object))
    (type $java$io$FileSystem (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$invoke$MethodHandles (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$invoke$LambdaMetafactory (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$ref$Reference (struct_subtype (field $runtimetype (ref $runtimetype)) (field $referent (ref $java$lang$Object)) $java$lang$Object))
    (type $de$mirkosertic$bytecoder$classlib$java$lang$TMath (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$Class (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$util$Arrays (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $jdk$internal$misc$CDS (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $jdk$internal$util$Preconditions (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$io$DefaultFileSystem (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$Character (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$System (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$AbstractStringBuilder (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$Throwable (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$Object))
    (type $java$util$Objects (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $de$mirkosertic$bytecoder$classlib$VM (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $jdk$internal$misc$Unsafe (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$nio$BufferMismatch (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $jdk$internal$misc$ScopedMemoryAccess (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$util$ImmutableCollections (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$Void (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $jdk$internal$access$foreign$MemorySegmentProxy (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $jdk$internal$access$SharedSecrets (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$io$FileDescriptor (struct_subtype (field $runtimetype (ref $runtimetype)) (field $fd i32) $java$lang$Object))
    (type $java$util$Dictionary (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$nio$charset$CharsetDecoder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $malformedInputAction (ref $java$lang$Object)) (field $unmappableCharacterAction (ref $java$lang$Object)) (field $maxCharsPerByte f32) (field $state i32) (field $replacement (ref $java$lang$Object)) (field $charset (ref $java$lang$Object)) (field $averageCharsPerByte f32) $java$lang$Object))
    (type $java$nio$Buffer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $mark i32) (field $position i32) (field $capacity i32) (field $segment (ref $java$lang$Object)) (field $limit i32) (field $address i64) $java$lang$Object))
    (type $de$mirkosertic$bytecoder$classlib$Array (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $de$mirkosertic$bytecoder$classlib$java$lang$ref$TReference (struct_subtype (field $runtimetype (ref $runtimetype)) (field $referent (ref $java$lang$Object)) $java$lang$Object))
    (type $java$lang$invoke$MethodHandles$Lookup (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$nio$charset$CharsetEncoder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $malformedInputAction (ref $java$lang$Object)) (field $unmappableCharacterAction (ref $java$lang$Object)) (field $state i32) (field $cachedDecoder (ref $java$lang$Object)) (field $charset (ref $java$lang$Object)) (field $averageBytesPerChar f32) (field $maxBytesPerChar f32) $java$lang$Object))
    (type $java$lang$ClassLoader (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $de$mirkosertic$bytecoder$cli$BytecoderCLITest (struct_subtype (field $runtimetype (ref $runtimetype)) (field $folder (ref $java$lang$Object)) $java$lang$Object))
    (type $java$lang$Math (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$Number (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$io$UnixFileSystem (struct_subtype (field $runtimetype (ref $runtimetype)) $java$io$FileSystem))
    (type $java$io$File (struct_subtype (field $runtimetype (ref $runtimetype)) (field $path (ref $java$lang$Object)) $java$lang$Object))
    (type $de$mirkosertic$bytecoder$classlib$VM$1 (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$ClassLoader))
    (type $java$lang$Error (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$Throwable))
    (type $java$lang$StringBuffer (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$AbstractStringBuilder))
    (type $java$lang$String (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$StringBuilder (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$AbstractStringBuilder))
    (type $java$nio$charset$Charset (struct_subtype (field $runtimetype (ref $runtimetype)) (field $canonicalName (ref $java$lang$Object)) $java$lang$Object))
    (type $java$lang$ref$WeakReference (struct_subtype (field $runtimetype (ref $runtimetype)) (field $referent (ref $java$lang$Object)) $java$lang$ref$Reference))
    (type $java$lang$Boolean (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$nio$ByteBuffer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $mark i32) (field $position i32) (field $capacity i32) (field $segment (ref $java$lang$Object)) (field $limit i32) (field $address i64) (field $offset i32) $java$nio$Buffer))
    (type $java$nio$CharBuffer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $mark i32) (field $position i32) (field $capacity i32) (field $segment (ref $java$lang$Object)) (field $limit i32) (field $address i64) (field $offset i32) $java$nio$Buffer))
    (type $java$nio$Buffer$1 (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$util$HashMap$Node (struct_subtype (field $runtimetype (ref $runtimetype)) (field $next (ref $java$lang$Object)) (field $hash i32) (field $key (ref $java$lang$Object)) (field $value (ref $java$lang$Object)) $java$lang$Object))
    (type $de$mirkosertic$bytecoder$classlib$BytecoderCharsetDecoder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $malformedInputAction (ref $java$lang$Object)) (field $unmappableCharacterAction (ref $java$lang$Object)) (field $maxCharsPerByte f32) (field $state i32) (field $replacement (ref $java$lang$Object)) (field $charset (ref $java$lang$Object)) (field $averageCharsPerByte f32) $java$nio$charset$CharsetDecoder))
    (type $java$util$Hashtable (struct_subtype (field $runtimetype (ref $runtimetype)) (field $modCount i32) $java$util$Dictionary))
    (type $java$util$AbstractMap (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $org$junit$rules$ExternalResource (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$Exception (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$Throwable))
    (type $de$mirkosertic$bytecoder$classlib$BytecoderCharsetEncoder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $malformedInputAction (ref $java$lang$Object)) (field $unmappableCharacterAction (ref $java$lang$Object)) (field $state i32) (field $cachedDecoder (ref $java$lang$Object)) (field $charset (ref $java$lang$Object)) (field $averageBytesPerChar f32) (field $maxBytesPerChar f32) $java$nio$charset$CharsetEncoder))
    (type $java$nio$charset$CoderMalfunctionError (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$Error))
    (type $java$lang$RuntimeException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$Exception))
    (type $java$lang$Float (struct_subtype (field $runtimetype (ref $runtimetype)) (field $value f32) $java$lang$Number))
    (type $java$util$LinkedHashMap$Entry (struct_subtype (field $runtimetype (ref $runtimetype)) (field $next (ref $java$lang$Object)) (field $hash i32) (field $key (ref $java$lang$Object)) (field $value (ref $java$lang$Object)) $java$util$HashMap$Node))
    (type $java$util$HashMap (struct_subtype (field $runtimetype (ref $runtimetype)) (field $loadFactor f32) (field $threshold i32) (field $size i32) (field $modCount i32) $java$util$AbstractMap))
    (type $java$nio$HeapByteBuffer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $mark i32) (field $position i32) (field $capacity i32) (field $segment (ref $java$lang$Object)) (field $limit i32) (field $address i64) (field $offset i32) $java$nio$ByteBuffer))
    (type $java$util$ImmutableCollections$AbstractImmutableMap (struct_subtype (field $runtimetype (ref $runtimetype)) $java$util$AbstractMap))
    (type $java$lang$Long (struct_subtype (field $runtimetype (ref $runtimetype)) (field $value i64) $java$lang$Number))
    (type $java$io$Writer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $lock (ref $java$lang$Object)) $java$lang$Object))
    (type $java$lang$Integer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $value i32) $java$lang$Number))
    (type $java$io$OutputStream (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $org$junit$rules$TemporaryFolder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $parentFolder (ref $java$lang$Object)) $org$junit$rules$ExternalResource))
    (type $java$util$AbstractCollection (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$io$InputStream (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$util$Properties (struct_subtype (field $runtimetype (ref $runtimetype)) (field $modCount i32) (field $map (ref $java$lang$Object)) (field $defaults (ref $java$lang$Object)) $java$util$Hashtable))
    (type $java$lang$AssertionError (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$Error))
    (type $java$lang$Byte (struct_subtype (field $runtimetype (ref $runtimetype)) (field $value i32) $java$lang$Number))
    (type $jdk$internal$misc$ScopedMemoryAccess$Scope$ScopedAccessError (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$Error))
    (type $java$util$concurrent$ConcurrentHashMap (struct_subtype (field $runtimetype (ref $runtimetype)) (field $delegate (ref $java$lang$Object)) $java$util$AbstractMap))
    (type $de$mirkosertic$bytecoder$classlib$BytecoderCharset (struct_subtype (field $runtimetype (ref $runtimetype)) (field $canonicalName (ref $java$lang$Object)) $java$nio$charset$Charset))
    (type $java$nio$HeapCharBuffer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $mark i32) (field $position i32) (field $capacity i32) (field $segment (ref $java$lang$Object)) (field $limit i32) (field $address i64) (field $offset i32) $java$nio$CharBuffer))
    (type $java$lang$VirtualMachineError (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$Error))
    (type $java$util$HashMap$TreeNode (struct_subtype (field $runtimetype (ref $runtimetype)) (field $next (ref $java$lang$Object)) (field $hash i32) (field $key (ref $java$lang$Object)) (field $value (ref $java$lang$Object)) (field $prev (ref $java$lang$Object)) (field $right (ref $java$lang$Object)) (field $left (ref $java$lang$Object)) (field $parent (ref $java$lang$Object)) $java$util$LinkedHashMap$Entry))
    (type $java$lang$IllegalStateException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$lang$InternalError (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$VirtualMachineError))
    (type $java$lang$UnsupportedOperationException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$io$FilterOutputStream (struct_subtype (field $runtimetype (ref $runtimetype)) (field $closeLock (ref $java$lang$Object)) (field $out (ref $java$lang$Object)) $java$io$OutputStream))
    (type $java$io$BufferedWriter (struct_subtype (field $runtimetype (ref $runtimetype)) (field $lock (ref $java$lang$Object)) (field $out (ref $java$lang$Object)) (field $nChars i32) (field $nextChar i32) $java$io$Writer))
    (type $java$lang$IndexOutOfBoundsException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$lang$IllegalArgumentException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$nio$BufferUnderflowException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$util$ImmutableCollections$AbstractImmutableCollection (struct_subtype (field $runtimetype (ref $runtimetype)) $java$util$AbstractCollection))
    (type $sun$nio$cs$StreamEncoder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $lock (ref $java$lang$Object)) (field $lcb (ref $java$lang$Object)) (field $out (ref $java$lang$Object)) (field $ch (ref $java$lang$Object)) (field $cs (ref $java$lang$Object)) (field $encoder (ref $java$lang$Object)) (field $bb (ref $java$lang$Object)) $java$io$Writer))
    (type $java$util$ConcurrentModificationException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$io$OutputStreamWriter (struct_subtype (field $runtimetype (ref $runtimetype)) (field $lock (ref $java$lang$Object)) (field $se (ref $java$lang$Object)) $java$io$Writer))
    (type $java$util$ImmutableCollections$MapN (struct_subtype (field $runtimetype (ref $runtimetype)) (field $size i32) $java$util$ImmutableCollections$AbstractImmutableMap))
    (type $java$lang$NullPointerException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$nio$BufferOverflowException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$io$FileInputStream (struct_subtype (field $runtimetype (ref $runtimetype)) (field $fd (ref $java$lang$Object)) (field $path (ref $java$lang$Object)) $java$io$InputStream))
    (type $java$io$FileOutputStream (struct_subtype (field $runtimetype (ref $runtimetype)) (field $fd (ref $java$lang$Object)) (field $path (ref $java$lang$Object)) $java$io$OutputStream))
    (type $java$io$PrintStream (struct_subtype (field $runtimetype (ref $runtimetype)) (field $closeLock (ref $java$lang$Object)) (field $out (ref $java$lang$Object)) (field $charOut (ref $java$lang$Object)) (field $textOut (ref $java$lang$Object)) $java$io$FilterOutputStream))
    (type $java$util$ImmutableCollections$AbstractImmutableList (struct_subtype (field $runtimetype (ref $runtimetype)) $java$util$ImmutableCollections$AbstractImmutableCollection))
    (type $java$lang$StringIndexOutOfBoundsException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$IndexOutOfBoundsException))
    (type $java$util$ImmutableCollections$AbstractImmutableSet (struct_subtype (field $runtimetype (ref $runtimetype)) $java$util$ImmutableCollections$AbstractImmutableCollection))
    (type $java$nio$ReadOnlyBufferException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$UnsupportedOperationException))
    (type $java$util$ImmutableCollections$SetN (struct_subtype (field $runtimetype (ref $runtimetype)) (field $size i32) $java$util$ImmutableCollections$AbstractImmutableSet))
    (type $java$util$ImmutableCollections$List12 (struct_subtype (field $runtimetype (ref $runtimetype)) (field $e0 (ref $java$lang$Object)) (field $e1 (ref $java$lang$Object)) $java$util$ImmutableCollections$AbstractImmutableList))
    (type $java$util$ImmutableCollections$ListN (struct_subtype (field $runtimetype (ref $runtimetype)) $java$util$ImmutableCollections$AbstractImmutableList))
    )
