(module $bytecoder
    (type $t0 (func (param i32) (result i32)))
    (type $t1 (array (mut i32)))
    (type $runtimetype (struct (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32)))
    (type $java$lang$Object (struct (field $runtimetype (ref $runtimetype))))
    (type $java$lang$Object_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $jdk$internal$misc$ScopedMemoryAccess (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $jdk$internal$misc$ScopedMemoryAccess_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $UNSAFE (ref null $java$lang$Object)) (field $theScopedMemoryAccess (ref null $java$lang$Object)) $runtimetype))
    (type $java$nio$charset$CoderResult$Cache (struct_subtype (field $runtimetype (ref $runtimetype)) (field $unmappable (ref null $java$lang$Object)) (field $malformed (ref null $java$lang$Object)) $java$lang$Object))
    (type $java$nio$charset$CoderResult$Cache_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $INSTANCE (ref null $java$lang$Object)) $runtimetype))
    (type $java$lang$invoke$MethodHandles$Lookup (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$invoke$MethodHandles$Lookup_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $de$mirkosertic$bytecoder$classlib$VM (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $de$mirkosertic$bytecoder$classlib$VM_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $SYSTEM_LOADER (ref null $java$lang$Object)) $runtimetype))
    (type $java$util$ImmutableCollections (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$util$ImmutableCollections_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $SALT32L i64) (field $EMPTY (ref null $java$lang$Object)) (field $EMPTY_LIST (ref null $java$lang$Object)) (field $EMPTY_LIST_NULLS (ref null $java$lang$Object)) (field $EMPTY_SET (ref null $java$lang$Object)) (field $EMPTY_MAP (ref null $java$lang$Object)) $runtimetype))
    (type $java$lang$AbstractStringBuilder (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$AbstractStringBuilder_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$Arrays (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$util$Arrays_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$nio$charset$CharsetEncoder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $malformedInputAction (ref null $java$lang$Object)) (field $unmappableCharacterAction (ref null $java$lang$Object)) (field $state i32) (field $cachedDecoder (ref null $java$lang$Object)) (field $charset (ref null $java$lang$Object)) (field $averageBytesPerChar f32) (field $maxBytesPerChar f32) $java$lang$Object))
    (type $java$nio$charset$CharsetEncoder_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$AutoCloseable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $de$mirkosertic$bytecoder$api$NativeReferenceHolder_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $jdk$internal$misc$CDS (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $jdk$internal$misc$CDS_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$Appendable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $jdk$internal$misc$Unsafe (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $jdk$internal$misc$Unsafe_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $INSTANCE (ref null $java$lang$Object)) (field $ARRAY_BOOLEAN_INDEX_SCALE i32) (field $ARRAY_BYTE_INDEX_SCALE i32) (field $ARRAY_CHAR_INDEX_SCALE i32) (field $ARRAY_SHORT_INDEX_SCALE i32) (field $ARRAY_INT_INDEX_SCALE i32) (field $ARRAY_LONG_INDEX_SCALE i32) (field $ARRAY_FLOAT_INDEX_SCALE i32) (field $ARRAY_DOUBLE_INDEX_SCALE i32) $runtimetype))
    (type $jdk$internal$access$foreign$MemorySegmentProxy (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $jdk$internal$access$foreign$MemorySegmentProxy_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$nio$BufferMismatch (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$nio$BufferMismatch_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $SCOPED_MEMORY_ACCESS (ref null $java$lang$Object)) $runtimetype))
    (type $java$lang$constant$Constable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$Class (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$Class_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$nio$Buffer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $mark i32) (field $position i32) (field $capacity i32) (field $segment (ref null $java$lang$Object)) (field $limit i32) (field $address i64) $java$lang$Object))
    (type $java$nio$Buffer_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $UNSAFE (ref null $java$lang$Object)) (field $SCOPED_MEMORY_ACCESS (ref null $java$lang$Object)) $runtimetype))
    (type $java$lang$ref$Reference (struct_subtype (field $runtimetype (ref $runtimetype)) (field $referent (ref null $java$lang$Object)) $java$lang$Object))
    (type $java$lang$ref$Reference_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $jdk$internal$access$SharedSecrets (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $jdk$internal$access$SharedSecrets_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $lookup (ref null $java$lang$Object)) (field $javaNioAccess (ref null $java$lang$Object)) $runtimetype))
    (type $java$lang$ClassLoader (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$ClassLoader_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $de$mirkosertic$bytecoder$classlib$java$lang$TMath (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $de$mirkosertic$bytecoder$classlib$java$lang$TMath_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$Throwable (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref null $java$lang$Object)) (field $cause (ref null $java$lang$Object)) $java$lang$Object))
    (type $java$lang$Throwable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$Cloneable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$io$FileDescriptor (struct_subtype (field $runtimetype (ref $runtimetype)) (field $fd i32) $java$lang$Object))
    (type $java$io$FileDescriptor_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $in (ref null $java$lang$Object)) (field $out (ref null $java$lang$Object)) (field $err (ref null $java$lang$Object)) $runtimetype))
    (type $java$nio$charset$CoderResult (struct_subtype (field $runtimetype (ref $runtimetype)) (field $type i32) (field $length i32) $java$lang$Object))
    (type $java$nio$charset$CoderResult_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $UNDERFLOW (ref null $java$lang$Object)) (field $OVERFLOW (ref null $java$lang$Object)) $runtimetype))
    (type $jdk$internal$util$ArraysSupport (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $jdk$internal$util$ArraysSupport_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $U (ref null $java$lang$Object)) (field $LOG2_ARRAY_BOOLEAN_INDEX_SCALE i32) (field $LOG2_ARRAY_BYTE_INDEX_SCALE i32) (field $LOG2_ARRAY_CHAR_INDEX_SCALE i32) (field $LOG2_ARRAY_SHORT_INDEX_SCALE i32) (field $LOG2_ARRAY_INT_INDEX_SCALE i32) (field $LOG2_ARRAY_LONG_INDEX_SCALE i32) (field $LOG2_ARRAY_FLOAT_INDEX_SCALE i32) (field $LOG2_ARRAY_DOUBLE_INDEX_SCALE i32) (field $LOG2_BYTE_BIT_SIZE i32) $runtimetype))
    (type $java$lang$invoke$LambdaMetafactory (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$invoke$LambdaMetafactory_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$function$BiFunction_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$RandomAccess_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$CharSequence_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$Objects (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$util$Objects_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $de$mirkosertic$bytecoder$cli$BytecoderCLITest (struct_subtype (field $runtimetype (ref $runtimetype)) (field $folder (ref null $java$lang$Object)) $java$lang$Object))
    (type $de$mirkosertic$bytecoder$cli$BytecoderCLITest_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$io$FileSystem (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$io$FileSystem_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$io$Serializable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$invoke$MethodHandles (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$invoke$MethodHandles_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$io$DefaultFileSystem (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$io$DefaultFileSystem_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$nio$ByteOrder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $name (ref null $java$lang$Object)) $java$lang$Object))
    (type $java$nio$ByteOrder_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $BIG_ENDIAN (ref null $java$lang$Object)) (field $LITTLE_ENDIAN (ref null $java$lang$Object)) (field $NATIVE_ORDER (ref null $java$lang$Object)) $runtimetype))
    (type $java$util$Map$Entry_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$Math (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$Math_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$Iterable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$io$Flushable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$nio$charset$CharsetDecoder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $malformedInputAction (ref null $java$lang$Object)) (field $unmappableCharacterAction (ref null $java$lang$Object)) (field $maxCharsPerByte f32) (field $state i32) (field $replacement (ref null $java$lang$Object)) (field $charset (ref null $java$lang$Object)) (field $averageCharsPerByte f32) $java$lang$Object))
    (type $java$nio$charset$CharsetDecoder_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $jdk$internal$util$Preconditions (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $jdk$internal$util$Preconditions_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$reflect$Type_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $org$junit$rules$TestRule_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$nio$charset$CodingErrorAction (struct_subtype (field $runtimetype (ref $runtimetype)) (field $name (ref null $java$lang$Object)) $java$lang$Object))
    (type $java$nio$charset$CodingErrorAction_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $IGNORE (ref null $java$lang$Object)) (field $REPLACE (ref null $java$lang$Object)) (field $REPORT (ref null $java$lang$Object)) $runtimetype))
    (type $jdk$internal$misc$ScopedMemoryAccess$Scope_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $jdk$internal$access$JavaNioAccess_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$Character (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$Character_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$function$Function_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$Dictionary (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$util$Dictionary_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $de$mirkosertic$bytecoder$classlib$Array (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $de$mirkosertic$bytecoder$classlib$Array_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$System (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$System_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $PROPERTIES (ref null $java$lang$Object)) (field $in (ref null $java$lang$Object)) (field $out (ref null $java$lang$Object)) (field $err (ref null $java$lang$Object)) $runtimetype))
    (type $java$lang$Comparable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$Readable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$Map_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$Void (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$Void_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $TYPE (ref null $java$lang$Object)) $runtimetype))
    (type $de$mirkosertic$bytecoder$classlib$java$lang$ref$TReference (struct_subtype (field $runtimetype (ref $runtimetype)) (field $referent (ref null $java$lang$Object)) $java$lang$Object))
    (type $de$mirkosertic$bytecoder$classlib$java$lang$ref$TReference_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$String (struct_subtype (field $runtimetype (ref $runtimetype)) (field $nativeObject anyref) $java$lang$Object))
    (type $java$lang$String_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$Boolean (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$Boolean_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $TRUE (ref null $java$lang$Object)) (field $FALSE (ref null $java$lang$Object)) (field $TYPE (ref null $java$lang$Object)) $runtimetype))
    (type $java$util$concurrent$ConcurrentMap_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$nio$Buffer$1 (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$nio$Buffer$1_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $de$mirkosertic$bytecoder$classlib$BytecoderCharsetDecoder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $malformedInputAction (ref null $java$lang$Object)) (field $unmappableCharacterAction (ref null $java$lang$Object)) (field $maxCharsPerByte f32) (field $state i32) (field $replacement (ref null $java$lang$Object)) (field $charset (ref null $java$lang$Object)) (field $averageCharsPerByte f32) $java$nio$charset$CharsetDecoder))
    (type $de$mirkosertic$bytecoder$classlib$BytecoderCharsetDecoder_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$io$UnixFileSystem (struct_subtype (field $runtimetype (ref $runtimetype)) $java$io$FileSystem))
    (type $java$io$UnixFileSystem_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$Exception (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref null $java$lang$Object)) (field $cause (ref null $java$lang$Object)) $java$lang$Throwable))
    (type $java$lang$Exception_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$Number (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$Number_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $org$junit$rules$ExternalResource (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $org$junit$rules$ExternalResource_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$nio$CharBuffer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $mark i32) (field $position i32) (field $capacity i32) (field $segment (ref null $java$lang$Object)) (field $limit i32) (field $address i64) (field $offset i32) $java$nio$Buffer))
    (type $java$nio$CharBuffer_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $ARRAY_BASE_OFFSET i64) $runtimetype))
    (type $java$nio$ByteBuffer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $mark i32) (field $position i32) (field $capacity i32) (field $segment (ref null $java$lang$Object)) (field $limit i32) (field $address i64) (field $offset i32) $java$nio$Buffer))
    (type $java$nio$ByteBuffer_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $ARRAY_BASE_OFFSET i64) $runtimetype))
    (type $de$mirkosertic$bytecoder$classlib$BytecoderCharsetEncoder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $malformedInputAction (ref null $java$lang$Object)) (field $unmappableCharacterAction (ref null $java$lang$Object)) (field $state i32) (field $cachedDecoder (ref null $java$lang$Object)) (field $charset (ref null $java$lang$Object)) (field $averageBytesPerChar f32) (field $maxBytesPerChar f32) $java$nio$charset$CharsetEncoder))
    (type $de$mirkosertic$bytecoder$classlib$BytecoderCharsetEncoder_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$HashMap$Node (struct_subtype (field $runtimetype (ref $runtimetype)) (field $next (ref null $java$lang$Object)) (field $hash i32) (field $key (ref null $java$lang$Object)) (field $value (ref null $java$lang$Object)) $java$lang$Object))
    (type $java$util$HashMap$Node_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$io$File (struct_subtype (field $runtimetype (ref $runtimetype)) (field $path (ref null $java$lang$Object)) $java$lang$Object))
    (type $java$io$File_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $fs (ref null $java$lang$Object)) (field $separatorChar i32) (field $separator (ref null $java$lang$Object)) (field $pathSeparatorChar i32) (field $pathSeparator (ref null $java$lang$Object)) (field $UNSAFE (ref null $java$lang$Object)) (field $PATH_OFFSET i64) (field $PREFIX_LENGTH_OFFSET i64) $runtimetype))
    (type $java$lang$StringBuffer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $nativeObject anyref) $java$lang$AbstractStringBuilder))
    (type $java$lang$StringBuffer_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$ref$WeakReference (struct_subtype (field $runtimetype (ref $runtimetype)) (field $referent (ref null $java$lang$Object)) $java$lang$ref$Reference))
    (type $java$lang$ref$WeakReference_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $de$mirkosertic$bytecoder$classlib$VM$1 (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$ClassLoader))
    (type $de$mirkosertic$bytecoder$classlib$VM$1_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$reflect$ParameterizedType_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$StringBuilder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $nativeObject anyref) $java$lang$AbstractStringBuilder))
    (type $java$lang$StringBuilder_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$AbstractMap (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$util$AbstractMap_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$Error (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref null $java$lang$Object)) (field $cause (ref null $java$lang$Object)) $java$lang$Throwable))
    (type $java$lang$Error_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$Collection_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$Hashtable (struct_subtype (field $runtimetype (ref $runtimetype)) (field $modCount i32) $java$util$Dictionary))
    (type $java$util$Hashtable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$io$Closeable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$nio$charset$Charset (struct_subtype (field $runtimetype (ref $runtimetype)) (field $canonicalName (ref null $java$lang$Object)) $java$lang$Object))
    (type $java$nio$charset$Charset_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $defaultCharset (ref null $java$lang$Object)) $runtimetype))
    (type $java$lang$Byte (struct_subtype (field $runtimetype (ref $runtimetype)) (field $value i32) $java$lang$Number))
    (type $java$lang$Byte_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $TYPE (ref null $java$lang$Object)) $runtimetype))
    (type $java$nio$charset$CoderMalfunctionError (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref null $java$lang$Object)) (field $cause (ref null $java$lang$Object)) $java$lang$Error))
    (type $java$nio$charset$CoderMalfunctionError_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$io$OutputStream (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$io$OutputStream_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$Set_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$concurrent$ConcurrentHashMap (struct_subtype (field $runtimetype (ref $runtimetype)) (field $delegate (ref null $java$lang$Object)) $java$util$AbstractMap))
    (type $java$util$concurrent$ConcurrentHashMap_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$nio$HeapCharBuffer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $mark i32) (field $position i32) (field $capacity i32) (field $segment (ref null $java$lang$Object)) (field $limit i32) (field $address i64) (field $offset i32) $java$nio$CharBuffer))
    (type $java$nio$HeapCharBuffer_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $ARRAY_BASE_OFFSET i64) (field $ARRAY_INDEX_SCALE i64) $runtimetype))
    (type $java$lang$Integer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $value i32) $java$lang$Number))
    (type $java$lang$Integer_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $TYPE (ref null $java$lang$Object)) $runtimetype))
    (type $java$io$InputStream (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$io$InputStream_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $org$junit$rules$TemporaryFolder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $parentFolder (ref null $java$lang$Object)) $org$junit$rules$ExternalResource))
    (type $org$junit$rules$TemporaryFolder_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$AssertionError (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref null $java$lang$Object)) (field $cause (ref null $java$lang$Object)) $java$lang$Error))
    (type $java$lang$AssertionError_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$AbstractCollection (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$util$AbstractCollection_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $jdk$internal$misc$ScopedMemoryAccess$Scope$ScopedAccessError (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref null $java$lang$Object)) (field $cause (ref null $java$lang$Object)) $java$lang$Error))
    (type $jdk$internal$misc$ScopedMemoryAccess$Scope$ScopedAccessError_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $INSTANCE (ref null $java$lang$Object)) $runtimetype))
    (type $java$util$Properties (struct_subtype (field $runtimetype (ref $runtimetype)) (field $modCount i32) (field $map (ref null $java$lang$Object)) (field $defaults (ref null $java$lang$Object)) $java$util$Hashtable))
    (type $java$util$Properties_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $UNSAFE (ref null $java$lang$Object)) $runtimetype))
    (type $java$util$HashMap (struct_subtype (field $runtimetype (ref $runtimetype)) (field $loadFactor f32) (field $threshold i32) (field $size i32) (field $modCount i32) $java$util$AbstractMap))
    (type $java$util$HashMap_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$Long (struct_subtype (field $runtimetype (ref $runtimetype)) (field $value i64) $java$lang$Number))
    (type $java$lang$Long_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $TYPE (ref null $java$lang$Object)) $runtimetype))
    (type $java$lang$RuntimeException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref null $java$lang$Object)) (field $cause (ref null $java$lang$Object)) $java$lang$Exception))
    (type $java$lang$RuntimeException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$ImmutableCollections$AbstractImmutableMap (struct_subtype (field $runtimetype (ref $runtimetype)) $java$util$AbstractMap))
    (type $java$util$ImmutableCollections$AbstractImmutableMap_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$List_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$LinkedHashMap$Entry (struct_subtype (field $runtimetype (ref $runtimetype)) (field $next (ref null $java$lang$Object)) (field $hash i32) (field $key (ref null $java$lang$Object)) (field $value (ref null $java$lang$Object)) $java$util$HashMap$Node))
    (type $java$util$LinkedHashMap$Entry_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$io$Writer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $lock (ref null $java$lang$Object)) $java$lang$Object))
    (type $java$io$Writer_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$Float (struct_subtype (field $runtimetype (ref $runtimetype)) (field $value f32) $java$lang$Number))
    (type $java$lang$Float_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $TYPE (ref null $java$lang$Object)) $runtimetype))
    (type $de$mirkosertic$bytecoder$classlib$BytecoderCharset (struct_subtype (field $runtimetype (ref $runtimetype)) (field $canonicalName (ref null $java$lang$Object)) $java$nio$charset$Charset))
    (type $de$mirkosertic$bytecoder$classlib$BytecoderCharset_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$nio$HeapByteBuffer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $mark i32) (field $position i32) (field $capacity i32) (field $segment (ref null $java$lang$Object)) (field $limit i32) (field $address i64) (field $offset i32) $java$nio$ByteBuffer))
    (type $java$nio$HeapByteBuffer_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $ARRAY_BASE_OFFSET i64) (field $ARRAY_INDEX_SCALE i64) $runtimetype))
    (type $java$lang$VirtualMachineError (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref null $java$lang$Object)) (field $cause (ref null $java$lang$Object)) $java$lang$Error))
    (type $java$lang$VirtualMachineError_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$io$FileOutputStream (struct_subtype (field $runtimetype (ref $runtimetype)) (field $fd (ref null $java$lang$Object)) (field $path (ref null $java$lang$Object)) $java$io$OutputStream))
    (type $java$io$FileOutputStream_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$io$FilterOutputStream (struct_subtype (field $runtimetype (ref $runtimetype)) (field $closeLock (ref null $java$lang$Object)) (field $out (ref null $java$lang$Object)) $java$io$OutputStream))
    (type $java$io$FilterOutputStream_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$InternalError (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref null $java$lang$Object)) (field $cause (ref null $java$lang$Object)) $java$lang$VirtualMachineError))
    (type $java$lang$InternalError_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$NullPointerException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref null $java$lang$Object)) (field $cause (ref null $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$lang$NullPointerException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$UnsupportedOperationException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref null $java$lang$Object)) (field $cause (ref null $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$lang$UnsupportedOperationException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$IllegalStateException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref null $java$lang$Object)) (field $cause (ref null $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$lang$IllegalStateException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$ConcurrentModificationException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref null $java$lang$Object)) (field $cause (ref null $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$util$ConcurrentModificationException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$ImmutableCollections$AbstractImmutableCollection (struct_subtype (field $runtimetype (ref $runtimetype)) $java$util$AbstractCollection))
    (type $java$util$ImmutableCollections$AbstractImmutableCollection_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$IndexOutOfBoundsException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref null $java$lang$Object)) (field $cause (ref null $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$lang$IndexOutOfBoundsException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$nio$BufferUnderflowException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref null $java$lang$Object)) (field $cause (ref null $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$nio$BufferUnderflowException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$io$BufferedWriter (struct_subtype (field $runtimetype (ref $runtimetype)) (field $lock (ref null $java$lang$Object)) (field $out (ref null $java$lang$Object)) (field $nChars i32) (field $nextChar i32) $java$io$Writer))
    (type $java$io$BufferedWriter_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) (field $defaultCharBufferSize i32) $runtimetype))
    (type $java$util$HashMap$TreeNode (struct_subtype (field $runtimetype (ref $runtimetype)) (field $next (ref null $java$lang$Object)) (field $hash i32) (field $key (ref null $java$lang$Object)) (field $value (ref null $java$lang$Object)) (field $prev (ref null $java$lang$Object)) (field $right (ref null $java$lang$Object)) (field $left (ref null $java$lang$Object)) (field $parent (ref null $java$lang$Object)) $java$util$LinkedHashMap$Entry))
    (type $java$util$HashMap$TreeNode_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$ImmutableCollections$MapN (struct_subtype (field $runtimetype (ref $runtimetype)) (field $size i32) $java$util$ImmutableCollections$AbstractImmutableMap))
    (type $java$util$ImmutableCollections$MapN_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$io$OutputStreamWriter (struct_subtype (field $runtimetype (ref $runtimetype)) (field $lock (ref null $java$lang$Object)) (field $se (ref null $java$lang$Object)) $java$io$Writer))
    (type $java$io$OutputStreamWriter_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$io$FileInputStream (struct_subtype (field $runtimetype (ref $runtimetype)) (field $fd (ref null $java$lang$Object)) (field $path (ref null $java$lang$Object)) $java$io$InputStream))
    (type $java$io$FileInputStream_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$IllegalArgumentException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref null $java$lang$Object)) (field $cause (ref null $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$lang$IllegalArgumentException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $sun$nio$cs$StreamEncoder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $lock (ref null $java$lang$Object)) (field $lcb (ref null $java$lang$Object)) (field $out (ref null $java$lang$Object)) (field $ch (ref null $java$lang$Object)) (field $cs (ref null $java$lang$Object)) (field $encoder (ref null $java$lang$Object)) (field $bb (ref null $java$lang$Object)) $java$io$Writer))
    (type $sun$nio$cs$StreamEncoder_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$nio$BufferOverflowException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref null $java$lang$Object)) (field $cause (ref null $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$nio$BufferOverflowException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$nio$ReadOnlyBufferException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref null $java$lang$Object)) (field $cause (ref null $java$lang$Object)) $java$lang$UnsupportedOperationException))
    (type $java$nio$ReadOnlyBufferException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$lang$StringIndexOutOfBoundsException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref null $java$lang$Object)) (field $cause (ref null $java$lang$Object)) $java$lang$IndexOutOfBoundsException))
    (type $java$lang$StringIndexOutOfBoundsException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$ImmutableCollections$AbstractImmutableList (struct_subtype (field $runtimetype (ref $runtimetype)) $java$util$ImmutableCollections$AbstractImmutableCollection))
    (type $java$util$ImmutableCollections$AbstractImmutableList_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$io$PrintStream (struct_subtype (field $runtimetype (ref $runtimetype)) (field $closeLock (ref null $java$lang$Object)) (field $out (ref null $java$lang$Object)) (field $charOut (ref null $java$lang$Object)) (field $textOut (ref null $java$lang$Object)) $java$io$FilterOutputStream))
    (type $java$io$PrintStream_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$ImmutableCollections$AbstractImmutableSet (struct_subtype (field $runtimetype (ref $runtimetype)) $java$util$ImmutableCollections$AbstractImmutableCollection))
    (type $java$util$ImmutableCollections$AbstractImmutableSet_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$ImmutableCollections$ListN (struct_subtype (field $runtimetype (ref $runtimetype)) $java$util$ImmutableCollections$AbstractImmutableList))
    (type $java$util$ImmutableCollections$ListN_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$ImmutableCollections$SetN (struct_subtype (field $runtimetype (ref $runtimetype)) (field $size i32) $java$util$ImmutableCollections$AbstractImmutableSet))
    (type $java$util$ImmutableCollections$SetN_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (type $java$util$ImmutableCollections$List12 (struct_subtype (field $runtimetype (ref $runtimetype)) (field $e0 (ref null $java$lang$Object)) (field $e1 (ref null $java$lang$Object)) $java$util$ImmutableCollections$AbstractImmutableList))
    (type $java$util$ImmutableCollections$List12_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref null $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) (field $initStatus i32) $runtimetype))
    (global $java$lang$Object_cls (ref $java$lang$Object_rtt) (struct.new $java$lang$Object_rtt (i32.const 0) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $jdk$internal$misc$ScopedMemoryAccess_cls (ref $jdk$internal$misc$ScopedMemoryAccess_rtt) (struct.new $jdk$internal$misc$ScopedMemoryAccess_rtt (i32.const 1) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object) (ref.null $java$lang$Object)))
    (global $java$nio$charset$CoderResult$Cache_cls (ref $java$nio$charset$CoderResult$Cache_rtt) (struct.new $java$nio$charset$CoderResult$Cache_rtt (i32.const 2) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object)))
    (global $java$lang$invoke$MethodHandles$Lookup_cls (ref $java$lang$invoke$MethodHandles$Lookup_rtt) (struct.new $java$lang$invoke$MethodHandles$Lookup_rtt (i32.const 3) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $de$mirkosertic$bytecoder$classlib$VM_cls (ref $de$mirkosertic$bytecoder$classlib$VM_rtt) (struct.new $de$mirkosertic$bytecoder$classlib$VM_rtt (i32.const 4) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object)))
    (global $java$util$ImmutableCollections_cls (ref $java$util$ImmutableCollections_rtt) (struct.new $java$util$ImmutableCollections_rtt (i32.const 5) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (i64.const 0) (ref.null $java$lang$Object) (ref.null $java$lang$Object) (ref.null $java$lang$Object) (ref.null $java$lang$Object) (ref.null $java$lang$Object)))
    (global $java$lang$AbstractStringBuilder_cls (ref $java$lang$AbstractStringBuilder_rtt) (struct.new $java$lang$AbstractStringBuilder_rtt (i32.const 6) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$Arrays_cls (ref $java$util$Arrays_rtt) (struct.new $java$util$Arrays_rtt (i32.const 7) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$nio$charset$CharsetEncoder_cls (ref $java$nio$charset$CharsetEncoder_rtt) (struct.new $java$nio$charset$CharsetEncoder_rtt (i32.const 8) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$AutoCloseable_cls (ref $java$lang$AutoCloseable_rtt) (struct.new $java$lang$AutoCloseable_rtt (i32.const 9) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $de$mirkosertic$bytecoder$api$NativeReferenceHolder_cls (ref $de$mirkosertic$bytecoder$api$NativeReferenceHolder_rtt) (struct.new $de$mirkosertic$bytecoder$api$NativeReferenceHolder_rtt (i32.const 10) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $jdk$internal$misc$CDS_cls (ref $jdk$internal$misc$CDS_rtt) (struct.new $jdk$internal$misc$CDS_rtt (i32.const 11) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$Appendable_cls (ref $java$lang$Appendable_rtt) (struct.new $java$lang$Appendable_rtt (i32.const 12) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $jdk$internal$misc$Unsafe_cls (ref $jdk$internal$misc$Unsafe_rtt) (struct.new $jdk$internal$misc$Unsafe_rtt (i32.const 13) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0)))
    (global $jdk$internal$access$foreign$MemorySegmentProxy_cls (ref $jdk$internal$access$foreign$MemorySegmentProxy_rtt) (struct.new $jdk$internal$access$foreign$MemorySegmentProxy_rtt (i32.const 14) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$nio$BufferMismatch_cls (ref $java$nio$BufferMismatch_rtt) (struct.new $java$nio$BufferMismatch_rtt (i32.const 15) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object)))
    (global $java$lang$constant$Constable_cls (ref $java$lang$constant$Constable_rtt) (struct.new $java$lang$constant$Constable_rtt (i32.const 16) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$Class_cls (ref $java$lang$Class_rtt) (struct.new $java$lang$Class_rtt (i32.const 17) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$nio$Buffer_cls (ref $java$nio$Buffer_rtt) (struct.new $java$nio$Buffer_rtt (i32.const 18) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object) (ref.null $java$lang$Object)))
    (global $java$lang$ref$Reference_cls (ref $java$lang$ref$Reference_rtt) (struct.new $java$lang$ref$Reference_rtt (i32.const 19) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $jdk$internal$access$SharedSecrets_cls (ref $jdk$internal$access$SharedSecrets_rtt) (struct.new $jdk$internal$access$SharedSecrets_rtt (i32.const 20) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object) (ref.null $java$lang$Object)))
    (global $java$lang$ClassLoader_cls (ref $java$lang$ClassLoader_rtt) (struct.new $java$lang$ClassLoader_rtt (i32.const 21) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $de$mirkosertic$bytecoder$classlib$java$lang$TMath_cls (ref $de$mirkosertic$bytecoder$classlib$java$lang$TMath_rtt) (struct.new $de$mirkosertic$bytecoder$classlib$java$lang$TMath_rtt (i32.const 22) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$Throwable_cls (ref $java$lang$Throwable_rtt) (struct.new $java$lang$Throwable_rtt (i32.const 23) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$Cloneable_cls (ref $java$lang$Cloneable_rtt) (struct.new $java$lang$Cloneable_rtt (i32.const 24) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$io$FileDescriptor_cls (ref $java$io$FileDescriptor_rtt) (struct.new $java$io$FileDescriptor_rtt (i32.const 25) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object) (ref.null $java$lang$Object) (ref.null $java$lang$Object)))
    (global $java$nio$charset$CoderResult_cls (ref $java$nio$charset$CoderResult_rtt) (struct.new $java$nio$charset$CoderResult_rtt (i32.const 26) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object) (ref.null $java$lang$Object)))
    (global $jdk$internal$util$ArraysSupport_cls (ref $jdk$internal$util$ArraysSupport_rtt) (struct.new $jdk$internal$util$ArraysSupport_rtt (i32.const 27) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0) (i32.const 0)))
    (global $java$lang$invoke$LambdaMetafactory_cls (ref $java$lang$invoke$LambdaMetafactory_rtt) (struct.new $java$lang$invoke$LambdaMetafactory_rtt (i32.const 28) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$function$BiFunction_cls (ref $java$util$function$BiFunction_rtt) (struct.new $java$util$function$BiFunction_rtt (i32.const 29) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$RandomAccess_cls (ref $java$util$RandomAccess_rtt) (struct.new $java$util$RandomAccess_rtt (i32.const 30) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$CharSequence_cls (ref $java$lang$CharSequence_rtt) (struct.new $java$lang$CharSequence_rtt (i32.const 31) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$Objects_cls (ref $java$util$Objects_rtt) (struct.new $java$util$Objects_rtt (i32.const 32) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $de$mirkosertic$bytecoder$cli$BytecoderCLITest_cls (ref $de$mirkosertic$bytecoder$cli$BytecoderCLITest_rtt) (struct.new $de$mirkosertic$bytecoder$cli$BytecoderCLITest_rtt (i32.const 33) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$io$FileSystem_cls (ref $java$io$FileSystem_rtt) (struct.new $java$io$FileSystem_rtt (i32.const 34) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$io$Serializable_cls (ref $java$io$Serializable_rtt) (struct.new $java$io$Serializable_rtt (i32.const 35) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$invoke$MethodHandles_cls (ref $java$lang$invoke$MethodHandles_rtt) (struct.new $java$lang$invoke$MethodHandles_rtt (i32.const 36) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$io$DefaultFileSystem_cls (ref $java$io$DefaultFileSystem_rtt) (struct.new $java$io$DefaultFileSystem_rtt (i32.const 37) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$nio$ByteOrder_cls (ref $java$nio$ByteOrder_rtt) (struct.new $java$nio$ByteOrder_rtt (i32.const 38) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object) (ref.null $java$lang$Object) (ref.null $java$lang$Object)))
    (global $java$util$Map$Entry_cls (ref $java$util$Map$Entry_rtt) (struct.new $java$util$Map$Entry_rtt (i32.const 39) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$Math_cls (ref $java$lang$Math_rtt) (struct.new $java$lang$Math_rtt (i32.const 40) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$Iterable_cls (ref $java$lang$Iterable_rtt) (struct.new $java$lang$Iterable_rtt (i32.const 41) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$io$Flushable_cls (ref $java$io$Flushable_rtt) (struct.new $java$io$Flushable_rtt (i32.const 42) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$nio$charset$CharsetDecoder_cls (ref $java$nio$charset$CharsetDecoder_rtt) (struct.new $java$nio$charset$CharsetDecoder_rtt (i32.const 43) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $jdk$internal$util$Preconditions_cls (ref $jdk$internal$util$Preconditions_rtt) (struct.new $jdk$internal$util$Preconditions_rtt (i32.const 44) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$reflect$Type_cls (ref $java$lang$reflect$Type_rtt) (struct.new $java$lang$reflect$Type_rtt (i32.const 45) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $org$junit$rules$TestRule_cls (ref $org$junit$rules$TestRule_rtt) (struct.new $org$junit$rules$TestRule_rtt (i32.const 46) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$nio$charset$CodingErrorAction_cls (ref $java$nio$charset$CodingErrorAction_rtt) (struct.new $java$nio$charset$CodingErrorAction_rtt (i32.const 47) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object) (ref.null $java$lang$Object) (ref.null $java$lang$Object)))
    (global $jdk$internal$misc$ScopedMemoryAccess$Scope_cls (ref $jdk$internal$misc$ScopedMemoryAccess$Scope_rtt) (struct.new $jdk$internal$misc$ScopedMemoryAccess$Scope_rtt (i32.const 48) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $jdk$internal$access$JavaNioAccess_cls (ref $jdk$internal$access$JavaNioAccess_rtt) (struct.new $jdk$internal$access$JavaNioAccess_rtt (i32.const 49) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$Character_cls (ref $java$lang$Character_rtt) (struct.new $java$lang$Character_rtt (i32.const 50) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$function$Function_cls (ref $java$util$function$Function_rtt) (struct.new $java$util$function$Function_rtt (i32.const 51) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$Dictionary_cls (ref $java$util$Dictionary_rtt) (struct.new $java$util$Dictionary_rtt (i32.const 52) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $de$mirkosertic$bytecoder$classlib$Array_cls (ref $de$mirkosertic$bytecoder$classlib$Array_rtt) (struct.new $de$mirkosertic$bytecoder$classlib$Array_rtt (i32.const 53) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$System_cls (ref $java$lang$System_rtt) (struct.new $java$lang$System_rtt (i32.const 54) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object) (ref.null $java$lang$Object) (ref.null $java$lang$Object) (ref.null $java$lang$Object)))
    (global $java$lang$Comparable_cls (ref $java$lang$Comparable_rtt) (struct.new $java$lang$Comparable_rtt (i32.const 55) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$Readable_cls (ref $java$lang$Readable_rtt) (struct.new $java$lang$Readable_rtt (i32.const 56) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$Map_cls (ref $java$util$Map_rtt) (struct.new $java$util$Map_rtt (i32.const 57) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$Void_cls (ref $java$lang$Void_rtt) (struct.new $java$lang$Void_rtt (i32.const 58) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object)))
    (global $de$mirkosertic$bytecoder$classlib$java$lang$ref$TReference_cls (ref $de$mirkosertic$bytecoder$classlib$java$lang$ref$TReference_rtt) (struct.new $de$mirkosertic$bytecoder$classlib$java$lang$ref$TReference_rtt (i32.const 59) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$String_cls (ref $java$lang$String_rtt) (struct.new $java$lang$String_rtt (i32.const 60) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$Boolean_cls (ref $java$lang$Boolean_rtt) (struct.new $java$lang$Boolean_rtt (i32.const 61) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object) (ref.null $java$lang$Object) (ref.null $java$lang$Object)))
    (global $java$util$concurrent$ConcurrentMap_cls (ref $java$util$concurrent$ConcurrentMap_rtt) (struct.new $java$util$concurrent$ConcurrentMap_rtt (i32.const 62) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$nio$Buffer$1_cls (ref $java$nio$Buffer$1_rtt) (struct.new $java$nio$Buffer$1_rtt (i32.const 63) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $de$mirkosertic$bytecoder$classlib$BytecoderCharsetDecoder_cls (ref $de$mirkosertic$bytecoder$classlib$BytecoderCharsetDecoder_rtt) (struct.new $de$mirkosertic$bytecoder$classlib$BytecoderCharsetDecoder_rtt (i32.const 64) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$io$UnixFileSystem_cls (ref $java$io$UnixFileSystem_rtt) (struct.new $java$io$UnixFileSystem_rtt (i32.const 65) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$Exception_cls (ref $java$lang$Exception_rtt) (struct.new $java$lang$Exception_rtt (i32.const 66) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$Number_cls (ref $java$lang$Number_rtt) (struct.new $java$lang$Number_rtt (i32.const 67) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $org$junit$rules$ExternalResource_cls (ref $org$junit$rules$ExternalResource_rtt) (struct.new $org$junit$rules$ExternalResource_rtt (i32.const 68) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$nio$CharBuffer_cls (ref $java$nio$CharBuffer_rtt) (struct.new $java$nio$CharBuffer_rtt (i32.const 69) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (i64.const 0)))
    (global $java$nio$ByteBuffer_cls (ref $java$nio$ByteBuffer_rtt) (struct.new $java$nio$ByteBuffer_rtt (i32.const 70) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (i64.const 0)))
    (global $de$mirkosertic$bytecoder$classlib$BytecoderCharsetEncoder_cls (ref $de$mirkosertic$bytecoder$classlib$BytecoderCharsetEncoder_rtt) (struct.new $de$mirkosertic$bytecoder$classlib$BytecoderCharsetEncoder_rtt (i32.const 71) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$HashMap$Node_cls (ref $java$util$HashMap$Node_rtt) (struct.new $java$util$HashMap$Node_rtt (i32.const 72) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$io$File_cls (ref $java$io$File_rtt) (struct.new $java$io$File_rtt (i32.const 73) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object) (i32.const 0) (ref.null $java$lang$Object) (i32.const 0) (ref.null $java$lang$Object) (ref.null $java$lang$Object) (i64.const 0) (i64.const 0)))
    (global $java$lang$StringBuffer_cls (ref $java$lang$StringBuffer_rtt) (struct.new $java$lang$StringBuffer_rtt (i32.const 74) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$ref$WeakReference_cls (ref $java$lang$ref$WeakReference_rtt) (struct.new $java$lang$ref$WeakReference_rtt (i32.const 75) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $de$mirkosertic$bytecoder$classlib$VM$1_cls (ref $de$mirkosertic$bytecoder$classlib$VM$1_rtt) (struct.new $de$mirkosertic$bytecoder$classlib$VM$1_rtt (i32.const 76) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$reflect$ParameterizedType_cls (ref $java$lang$reflect$ParameterizedType_rtt) (struct.new $java$lang$reflect$ParameterizedType_rtt (i32.const 77) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$StringBuilder_cls (ref $java$lang$StringBuilder_rtt) (struct.new $java$lang$StringBuilder_rtt (i32.const 78) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$AbstractMap_cls (ref $java$util$AbstractMap_rtt) (struct.new $java$util$AbstractMap_rtt (i32.const 79) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$Error_cls (ref $java$lang$Error_rtt) (struct.new $java$lang$Error_rtt (i32.const 80) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$Collection_cls (ref $java$util$Collection_rtt) (struct.new $java$util$Collection_rtt (i32.const 81) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$Hashtable_cls (ref $java$util$Hashtable_rtt) (struct.new $java$util$Hashtable_rtt (i32.const 82) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$io$Closeable_cls (ref $java$io$Closeable_rtt) (struct.new $java$io$Closeable_rtt (i32.const 83) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$nio$charset$Charset_cls (ref $java$nio$charset$Charset_rtt) (struct.new $java$nio$charset$Charset_rtt (i32.const 84) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object)))
    (global $java$lang$Byte_cls (ref $java$lang$Byte_rtt) (struct.new $java$lang$Byte_rtt (i32.const 85) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object)))
    (global $java$nio$charset$CoderMalfunctionError_cls (ref $java$nio$charset$CoderMalfunctionError_rtt) (struct.new $java$nio$charset$CoderMalfunctionError_rtt (i32.const 86) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$io$OutputStream_cls (ref $java$io$OutputStream_rtt) (struct.new $java$io$OutputStream_rtt (i32.const 87) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$Set_cls (ref $java$util$Set_rtt) (struct.new $java$util$Set_rtt (i32.const 88) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$concurrent$ConcurrentHashMap_cls (ref $java$util$concurrent$ConcurrentHashMap_rtt) (struct.new $java$util$concurrent$ConcurrentHashMap_rtt (i32.const 89) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$nio$HeapCharBuffer_cls (ref $java$nio$HeapCharBuffer_rtt) (struct.new $java$nio$HeapCharBuffer_rtt (i32.const 90) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (i64.const 0) (i64.const 0)))
    (global $java$lang$Integer_cls (ref $java$lang$Integer_rtt) (struct.new $java$lang$Integer_rtt (i32.const 91) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object)))
    (global $java$io$InputStream_cls (ref $java$io$InputStream_rtt) (struct.new $java$io$InputStream_rtt (i32.const 92) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $org$junit$rules$TemporaryFolder_cls (ref $org$junit$rules$TemporaryFolder_rtt) (struct.new $org$junit$rules$TemporaryFolder_rtt (i32.const 93) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$AssertionError_cls (ref $java$lang$AssertionError_rtt) (struct.new $java$lang$AssertionError_rtt (i32.const 94) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$AbstractCollection_cls (ref $java$util$AbstractCollection_rtt) (struct.new $java$util$AbstractCollection_rtt (i32.const 95) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $jdk$internal$misc$ScopedMemoryAccess$Scope$ScopedAccessError_cls (ref $jdk$internal$misc$ScopedMemoryAccess$Scope$ScopedAccessError_rtt) (struct.new $jdk$internal$misc$ScopedMemoryAccess$Scope$ScopedAccessError_rtt (i32.const 96) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object)))
    (global $java$util$Properties_cls (ref $java$util$Properties_rtt) (struct.new $java$util$Properties_rtt (i32.const 97) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object)))
    (global $java$util$HashMap_cls (ref $java$util$HashMap_rtt) (struct.new $java$util$HashMap_rtt (i32.const 98) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$Long_cls (ref $java$lang$Long_rtt) (struct.new $java$lang$Long_rtt (i32.const 99) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object)))
    (global $java$lang$RuntimeException_cls (ref $java$lang$RuntimeException_rtt) (struct.new $java$lang$RuntimeException_rtt (i32.const 100) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$ImmutableCollections$AbstractImmutableMap_cls (ref $java$util$ImmutableCollections$AbstractImmutableMap_rtt) (struct.new $java$util$ImmutableCollections$AbstractImmutableMap_rtt (i32.const 101) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$List_cls (ref $java$util$List_rtt) (struct.new $java$util$List_rtt (i32.const 102) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$LinkedHashMap$Entry_cls (ref $java$util$LinkedHashMap$Entry_rtt) (struct.new $java$util$LinkedHashMap$Entry_rtt (i32.const 103) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$io$Writer_cls (ref $java$io$Writer_rtt) (struct.new $java$io$Writer_rtt (i32.const 104) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$Float_cls (ref $java$lang$Float_rtt) (struct.new $java$lang$Float_rtt (i32.const 105) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (ref.null $java$lang$Object)))
    (global $de$mirkosertic$bytecoder$classlib$BytecoderCharset_cls (ref $de$mirkosertic$bytecoder$classlib$BytecoderCharset_rtt) (struct.new $de$mirkosertic$bytecoder$classlib$BytecoderCharset_rtt (i32.const 106) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$nio$HeapByteBuffer_cls (ref $java$nio$HeapByteBuffer_rtt) (struct.new $java$nio$HeapByteBuffer_rtt (i32.const 107) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (i64.const 0) (i64.const 0)))
    (global $java$lang$VirtualMachineError_cls (ref $java$lang$VirtualMachineError_rtt) (struct.new $java$lang$VirtualMachineError_rtt (i32.const 108) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$io$FileOutputStream_cls (ref $java$io$FileOutputStream_rtt) (struct.new $java$io$FileOutputStream_rtt (i32.const 109) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$io$FilterOutputStream_cls (ref $java$io$FilterOutputStream_rtt) (struct.new $java$io$FilterOutputStream_rtt (i32.const 110) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$InternalError_cls (ref $java$lang$InternalError_rtt) (struct.new $java$lang$InternalError_rtt (i32.const 111) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$NullPointerException_cls (ref $java$lang$NullPointerException_rtt) (struct.new $java$lang$NullPointerException_rtt (i32.const 112) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$UnsupportedOperationException_cls (ref $java$lang$UnsupportedOperationException_rtt) (struct.new $java$lang$UnsupportedOperationException_rtt (i32.const 113) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$IllegalStateException_cls (ref $java$lang$IllegalStateException_rtt) (struct.new $java$lang$IllegalStateException_rtt (i32.const 114) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$ConcurrentModificationException_cls (ref $java$util$ConcurrentModificationException_rtt) (struct.new $java$util$ConcurrentModificationException_rtt (i32.const 115) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$ImmutableCollections$AbstractImmutableCollection_cls (ref $java$util$ImmutableCollections$AbstractImmutableCollection_rtt) (struct.new $java$util$ImmutableCollections$AbstractImmutableCollection_rtt (i32.const 116) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$IndexOutOfBoundsException_cls (ref $java$lang$IndexOutOfBoundsException_rtt) (struct.new $java$lang$IndexOutOfBoundsException_rtt (i32.const 117) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$nio$BufferUnderflowException_cls (ref $java$nio$BufferUnderflowException_rtt) (struct.new $java$nio$BufferUnderflowException_rtt (i32.const 118) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$io$BufferedWriter_cls (ref $java$io$BufferedWriter_rtt) (struct.new $java$io$BufferedWriter_rtt (i32.const 119) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0) (i32.const 0)))
    (global $java$util$HashMap$TreeNode_cls (ref $java$util$HashMap$TreeNode_rtt) (struct.new $java$util$HashMap$TreeNode_rtt (i32.const 120) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$ImmutableCollections$MapN_cls (ref $java$util$ImmutableCollections$MapN_rtt) (struct.new $java$util$ImmutableCollections$MapN_rtt (i32.const 121) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$io$OutputStreamWriter_cls (ref $java$io$OutputStreamWriter_rtt) (struct.new $java$io$OutputStreamWriter_rtt (i32.const 122) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$io$FileInputStream_cls (ref $java$io$FileInputStream_rtt) (struct.new $java$io$FileInputStream_rtt (i32.const 123) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$IllegalArgumentException_cls (ref $java$lang$IllegalArgumentException_rtt) (struct.new $java$lang$IllegalArgumentException_rtt (i32.const 124) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $sun$nio$cs$StreamEncoder_cls (ref $sun$nio$cs$StreamEncoder_rtt) (struct.new $sun$nio$cs$StreamEncoder_rtt (i32.const 125) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$nio$BufferOverflowException_cls (ref $java$nio$BufferOverflowException_rtt) (struct.new $java$nio$BufferOverflowException_rtt (i32.const 126) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$nio$ReadOnlyBufferException_cls (ref $java$nio$ReadOnlyBufferException_rtt) (struct.new $java$nio$ReadOnlyBufferException_rtt (i32.const 127) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$lang$StringIndexOutOfBoundsException_cls (ref $java$lang$StringIndexOutOfBoundsException_rtt) (struct.new $java$lang$StringIndexOutOfBoundsException_rtt (i32.const 128) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$ImmutableCollections$AbstractImmutableList_cls (ref $java$util$ImmutableCollections$AbstractImmutableList_rtt) (struct.new $java$util$ImmutableCollections$AbstractImmutableList_rtt (i32.const 129) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$io$PrintStream_cls (ref $java$io$PrintStream_rtt) (struct.new $java$io$PrintStream_rtt (i32.const 130) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$ImmutableCollections$AbstractImmutableSet_cls (ref $java$util$ImmutableCollections$AbstractImmutableSet_rtt) (struct.new $java$util$ImmutableCollections$AbstractImmutableSet_rtt (i32.const 131) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$ImmutableCollections$ListN_cls (ref $java$util$ImmutableCollections$ListN_rtt) (struct.new $java$util$ImmutableCollections$ListN_rtt (i32.const 132) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$ImmutableCollections$SetN_cls (ref $java$util$ImmutableCollections$SetN_rtt) (struct.new $java$util$ImmutableCollections$SetN_rtt (i32.const 133) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (global $java$util$ImmutableCollections$List12_cls (ref $java$util$ImmutableCollections$List12_rtt) (struct.new $java$util$ImmutableCollections$List12_rtt (i32.const 134) (ref.null $t1) (i32.const -1) (ref.null $t0) (i32.const 0)))
    (func $java$lang$Object_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $jdk$internal$misc$ScopedMemoryAccess_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$nio$charset$CoderResult$Cache_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$invoke$MethodHandles$Lookup_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $de$mirkosertic$bytecoder$classlib$VM_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$ImmutableCollections_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$AbstractStringBuilder_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$Arrays_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$nio$charset$CharsetEncoder_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$AutoCloseable_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $de$mirkosertic$bytecoder$api$NativeReferenceHolder_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $jdk$internal$misc$CDS_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$Appendable_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $jdk$internal$misc$Unsafe_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $jdk$internal$access$foreign$MemorySegmentProxy_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$nio$BufferMismatch_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$constant$Constable_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$Class_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$nio$Buffer_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$ref$Reference_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $jdk$internal$access$SharedSecrets_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$ClassLoader_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $de$mirkosertic$bytecoder$classlib$java$lang$TMath_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$Throwable_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$Cloneable_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$io$FileDescriptor_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$nio$charset$CoderResult_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $jdk$internal$util$ArraysSupport_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$invoke$LambdaMetafactory_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$function$BiFunction_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$RandomAccess_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$CharSequence_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$Objects_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $de$mirkosertic$bytecoder$cli$BytecoderCLITest_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$io$FileSystem_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$io$Serializable_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$invoke$MethodHandles_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$io$DefaultFileSystem_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$nio$ByteOrder_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$Map$Entry_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$Math_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$Iterable_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$io$Flushable_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$nio$charset$CharsetDecoder_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $jdk$internal$util$Preconditions_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$reflect$Type_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $org$junit$rules$TestRule_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$nio$charset$CodingErrorAction_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $jdk$internal$misc$ScopedMemoryAccess$Scope_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $jdk$internal$access$JavaNioAccess_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$Character_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$function$Function_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$Dictionary_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $de$mirkosertic$bytecoder$classlib$Array_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$System_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$Comparable_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$Readable_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$Map_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$Void_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $de$mirkosertic$bytecoder$classlib$java$lang$ref$TReference_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$String_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$Boolean_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$concurrent$ConcurrentMap_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$nio$Buffer$1_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $de$mirkosertic$bytecoder$classlib$BytecoderCharsetDecoder_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$io$UnixFileSystem_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$Exception_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$Number_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $org$junit$rules$ExternalResource_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$nio$CharBuffer_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$nio$ByteBuffer_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $de$mirkosertic$bytecoder$classlib$BytecoderCharsetEncoder_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$HashMap$Node_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$io$File_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$StringBuffer_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$ref$WeakReference_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $de$mirkosertic$bytecoder$classlib$VM$1_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$reflect$ParameterizedType_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$StringBuilder_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$AbstractMap_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$Error_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$Collection_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$Hashtable_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$io$Closeable_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$nio$charset$Charset_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$Byte_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$nio$charset$CoderMalfunctionError_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$io$OutputStream_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$Set_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$concurrent$ConcurrentHashMap_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$nio$HeapCharBuffer_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$Integer_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$io$InputStream_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $org$junit$rules$TemporaryFolder_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$AssertionError_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$AbstractCollection_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $jdk$internal$misc$ScopedMemoryAccess$Scope$ScopedAccessError_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$Properties_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$HashMap_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$Long_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$RuntimeException_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$ImmutableCollections$AbstractImmutableMap_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$List_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$LinkedHashMap$Entry_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$io$Writer_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$Float_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $de$mirkosertic$bytecoder$classlib$BytecoderCharset_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$nio$HeapByteBuffer_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$VirtualMachineError_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$io$FileOutputStream_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$io$FilterOutputStream_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$InternalError_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$NullPointerException_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$UnsupportedOperationException_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$IllegalStateException_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$ConcurrentModificationException_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$ImmutableCollections$AbstractImmutableCollection_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$IndexOutOfBoundsException_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$nio$BufferUnderflowException_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$io$BufferedWriter_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$HashMap$TreeNode_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$ImmutableCollections$MapN_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$io$OutputStreamWriter_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$io$FileInputStream_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$IllegalArgumentException_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $sun$nio$cs$StreamEncoder_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$nio$BufferOverflowException_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$nio$ReadOnlyBufferException_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$lang$StringIndexOutOfBoundsException_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$ImmutableCollections$AbstractImmutableList_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$io$PrintStream_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$ImmutableCollections$AbstractImmutableSet_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$ImmutableCollections$ListN_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$ImmutableCollections$SetN_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    (func $java$util$ImmutableCollections$List12_vt (type $t0) (param $methodid i32) (result i32)
        (unreachable))
    )