(module $bytecoder
    (type $t0 (func (param i32) (result i32)))
    (type $t1 (array (mut i32)))
    (type $runtimetype (struct (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0))))
    (type $java$lang$Object (struct (field $runtimetype (ref $runtimetype))))
    (type $java$lang$Object_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref null $t0)) $runtimetype))


    (global $java$lang$Object_cls (ref $java$lang$Object_rtt)
        (struct.new $java$lang$Object_rtt
            (i32.const 0)
            (array.new $t1 (i32.const 1) (i32.const 10))
            (i32.const -1)
            (ref.null $t0)
        )
    )

    (type $java$nio$charset$CodingErrorAction (struct_subtype (field $runtimetype (ref $runtimetype)) (field $name (ref $java$lang$Object)) $java$lang$Object))
    (type $java$nio$charset$CodingErrorAction_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $IGNORE (ref $java$lang$Object)) (field $REPLACE (ref $java$lang$Object)) (field $REPORT (ref $java$lang$Object)) $runtimetype))
    (type $java$lang$Comparable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$nio$ByteOrder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $name (ref $java$lang$Object)) $java$lang$Object))
    (type $java$nio$ByteOrder_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $BIG_ENDIAN (ref $java$lang$Object)) (field $LITTLE_ENDIAN (ref $java$lang$Object)) (field $NATIVE_ORDER (ref $java$lang$Object)) $runtimetype))
    (type $java$io$Flushable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$nio$charset$CoderResult (struct_subtype (field $runtimetype (ref $runtimetype)) (field $type i32) (field $length i32) $java$lang$Object))
    (type $java$nio$charset$CoderResult_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $UNDERFLOW (ref $java$lang$Object)) (field $OVERFLOW (ref $java$lang$Object)) $runtimetype))
    (type $jdk$internal$util$ArraysSupport (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $jdk$internal$util$ArraysSupport_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $U (ref $java$lang$Object)) (field $LOG2_ARRAY_BOOLEAN_INDEX_SCALE i32) (field $LOG2_ARRAY_BYTE_INDEX_SCALE i32) (field $LOG2_ARRAY_CHAR_INDEX_SCALE i32) (field $LOG2_ARRAY_SHORT_INDEX_SCALE i32) (field $LOG2_ARRAY_INT_INDEX_SCALE i32) (field $LOG2_ARRAY_LONG_INDEX_SCALE i32) (field $LOG2_ARRAY_FLOAT_INDEX_SCALE i32) (field $LOG2_ARRAY_DOUBLE_INDEX_SCALE i32) (field $LOG2_BYTE_BIT_SIZE i32) $runtimetype))
    (type $java$nio$charset$CoderResult$Cache (struct_subtype (field $runtimetype (ref $runtimetype)) (field $unmappable (ref $java$lang$Object)) (field $malformed (ref $java$lang$Object)) $java$lang$Object))
    (type $java$nio$charset$CoderResult$Cache_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $INSTANCE (ref $java$lang$Object)) $runtimetype))
    (type $java$lang$constant$Constable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$io$FileSystem (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$io$FileSystem_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$invoke$MethodHandles (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$invoke$MethodHandles_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$invoke$LambdaMetafactory (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$invoke$LambdaMetafactory_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$ref$Reference (struct_subtype (field $runtimetype (ref $runtimetype)) (field $referent (ref $java$lang$Object)) $java$lang$Object))
    (type $java$lang$ref$Reference_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $org$junit$rules$TestRule_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $de$mirkosertic$bytecoder$classlib$java$lang$TMath (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $de$mirkosertic$bytecoder$classlib$java$lang$TMath_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$CharSequence_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$Iterable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$Class (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$Class_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$Arrays (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$util$Arrays_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $jdk$internal$misc$CDS (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $jdk$internal$misc$CDS_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$Cloneable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$io$Serializable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $jdk$internal$util$Preconditions (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $jdk$internal$util$Preconditions_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$Appendable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$Map$Entry_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$io$DefaultFileSystem (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$io$DefaultFileSystem_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $jdk$internal$misc$ScopedMemoryAccess$Scope_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$Character (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$Character_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$System (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$System_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $PROPERTIES (ref $java$lang$Object)) (field $in (ref $java$lang$Object)) (field $out (ref $java$lang$Object)) (field $err (ref $java$lang$Object)) $runtimetype))
    (type $java$lang$AbstractStringBuilder (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$AbstractStringBuilder_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$Throwable (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$Object))
    (type $java$lang$Throwable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$Objects (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$util$Objects_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $de$mirkosertic$bytecoder$classlib$VM (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $de$mirkosertic$bytecoder$classlib$VM_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $SYSTEM_LOADER (ref $java$lang$Object)) $runtimetype))
    (type $jdk$internal$misc$Unsafe (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $jdk$internal$misc$Unsafe_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $INSTANCE (ref $java$lang$Object)) (field $ARRAY_BOOLEAN_INDEX_SCALE i32) (field $ARRAY_BYTE_INDEX_SCALE i32) (field $ARRAY_CHAR_INDEX_SCALE i32) (field $ARRAY_SHORT_INDEX_SCALE i32) (field $ARRAY_INT_INDEX_SCALE i32) (field $ARRAY_LONG_INDEX_SCALE i32) (field $ARRAY_FLOAT_INDEX_SCALE i32) (field $ARRAY_DOUBLE_INDEX_SCALE i32) $runtimetype))
    (type $jdk$internal$access$JavaNioAccess_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$nio$BufferMismatch (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$nio$BufferMismatch_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $SCOPED_MEMORY_ACCESS (ref $java$lang$Object)) $runtimetype))
    (type $jdk$internal$misc$ScopedMemoryAccess (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $jdk$internal$misc$ScopedMemoryAccess_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $UNSAFE (ref $java$lang$Object)) (field $theScopedMemoryAccess (ref $java$lang$Object)) $runtimetype))
    (type $java$lang$Readable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$ImmutableCollections (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$util$ImmutableCollections_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $SALT32L i64) (field $EMPTY (ref $java$lang$Object)) (field $EMPTY_LIST (ref $java$lang$Object)) (field $EMPTY_LIST_NULLS (ref $java$lang$Object)) (field $EMPTY_SET (ref $java$lang$Object)) (field $EMPTY_MAP (ref $java$lang$Object)) $runtimetype))
    (type $java$util$function$Function_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$Void (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$Void_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $TYPE (ref $java$lang$Object)) $runtimetype))
    (type $java$util$Map_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $de$mirkosertic$bytecoder$api$NativeReferenceHolder_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$reflect$Type_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $jdk$internal$access$foreign$MemorySegmentProxy (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $jdk$internal$access$foreign$MemorySegmentProxy_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$function$BiFunction_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $jdk$internal$access$SharedSecrets (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $jdk$internal$access$SharedSecrets_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $lookup (ref $java$lang$Object)) (field $javaNioAccess (ref $java$lang$Object)) $runtimetype))
    (type $java$io$FileDescriptor (struct_subtype (field $runtimetype (ref $runtimetype)) (field $fd i32) $java$lang$Object))
    (type $java$io$FileDescriptor_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $in (ref $java$lang$Object)) (field $out (ref $java$lang$Object)) (field $err (ref $java$lang$Object)) $runtimetype))
    (type $java$util$Dictionary (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$util$Dictionary_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$nio$charset$CharsetDecoder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $malformedInputAction (ref $java$lang$Object)) (field $unmappableCharacterAction (ref $java$lang$Object)) (field $maxCharsPerByte f32) (field $state i32) (field $replacement (ref $java$lang$Object)) (field $charset (ref $java$lang$Object)) (field $averageCharsPerByte f32) $java$lang$Object))
    (type $java$nio$charset$CharsetDecoder_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$nio$Buffer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $mark i32) (field $position i32) (field $capacity i32) (field $segment (ref $java$lang$Object)) (field $limit i32) (field $address i64) $java$lang$Object))
    (type $java$nio$Buffer_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $UNSAFE (ref $java$lang$Object)) (field $SCOPED_MEMORY_ACCESS (ref $java$lang$Object)) $runtimetype))
    (type $de$mirkosertic$bytecoder$classlib$Array (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $de$mirkosertic$bytecoder$classlib$Array_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$AutoCloseable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $de$mirkosertic$bytecoder$classlib$java$lang$ref$TReference (struct_subtype (field $runtimetype (ref $runtimetype)) (field $referent (ref $java$lang$Object)) $java$lang$Object))
    (type $de$mirkosertic$bytecoder$classlib$java$lang$ref$TReference_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$invoke$MethodHandles$Lookup (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$invoke$MethodHandles$Lookup_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$nio$charset$CharsetEncoder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $malformedInputAction (ref $java$lang$Object)) (field $unmappableCharacterAction (ref $java$lang$Object)) (field $state i32) (field $cachedDecoder (ref $java$lang$Object)) (field $charset (ref $java$lang$Object)) (field $averageBytesPerChar f32) (field $maxBytesPerChar f32) $java$lang$Object))
    (type $java$nio$charset$CharsetEncoder_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$ClassLoader (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$ClassLoader_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $de$mirkosertic$bytecoder$cli$BytecoderCLITest (struct_subtype (field $runtimetype (ref $runtimetype)) (field $folder (ref $java$lang$Object)) $java$lang$Object))
    (type $de$mirkosertic$bytecoder$cli$BytecoderCLITest_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$RandomAccess_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$Math (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$Math_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$Number (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$Number_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$reflect$ParameterizedType_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$io$UnixFileSystem (struct_subtype (field $runtimetype (ref $runtimetype)) $java$io$FileSystem))
    (type $java$io$UnixFileSystem_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$io$File (struct_subtype (field $runtimetype (ref $runtimetype)) (field $path (ref $java$lang$Object)) $java$lang$Object))
    (type $java$io$File_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $fs (ref $java$lang$Object)) (field $separatorChar i32) (field $separator (ref $java$lang$Object)) (field $pathSeparatorChar i32) (field $pathSeparator (ref $java$lang$Object)) (field $UNSAFE (ref $java$lang$Object)) (field $PATH_OFFSET i64) (field $PREFIX_LENGTH_OFFSET i64) $runtimetype))
    (type $de$mirkosertic$bytecoder$classlib$VM$1 (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$ClassLoader))
    (type $de$mirkosertic$bytecoder$classlib$VM$1_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$Error (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$Throwable))
    (type $java$lang$Error_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$StringBuffer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $nativeObject anyref) $java$lang$AbstractStringBuilder))
    (type $java$lang$StringBuffer_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$String (struct_subtype (field $runtimetype (ref $runtimetype)) (field $nativeObject anyref) $java$lang$Object))
    (type $java$lang$String_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$concurrent$ConcurrentMap_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$StringBuilder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $nativeObject anyref) $java$lang$AbstractStringBuilder))
    (type $java$lang$StringBuilder_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$io$Closeable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$nio$charset$Charset (struct_subtype (field $runtimetype (ref $runtimetype)) (field $canonicalName (ref $java$lang$Object)) $java$lang$Object))
    (type $java$nio$charset$Charset_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $defaultCharset (ref $java$lang$Object)) $runtimetype))
    (type $java$lang$ref$WeakReference (struct_subtype (field $runtimetype (ref $runtimetype)) (field $referent (ref $java$lang$Object)) $java$lang$ref$Reference))
    (type $java$lang$ref$WeakReference_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$Collection_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$Boolean (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$lang$Boolean_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $TRUE (ref $java$lang$Object)) (field $FALSE (ref $java$lang$Object)) (field $TYPE (ref $java$lang$Object)) $runtimetype))
    (type $java$nio$ByteBuffer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $mark i32) (field $position i32) (field $capacity i32) (field $segment (ref $java$lang$Object)) (field $limit i32) (field $address i64) (field $offset i32) $java$nio$Buffer))
    (type $java$nio$ByteBuffer_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $ARRAY_BASE_OFFSET i64) $runtimetype))
    (type $java$nio$CharBuffer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $mark i32) (field $position i32) (field $capacity i32) (field $segment (ref $java$lang$Object)) (field $limit i32) (field $address i64) (field $offset i32) $java$nio$Buffer))
    (type $java$nio$CharBuffer_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $ARRAY_BASE_OFFSET i64) $runtimetype))
    (type $java$nio$Buffer$1 (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$nio$Buffer$1_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$HashMap$Node (struct_subtype (field $runtimetype (ref $runtimetype)) (field $next (ref $java$lang$Object)) (field $hash i32) (field $key (ref $java$lang$Object)) (field $value (ref $java$lang$Object)) $java$lang$Object))
    (type $java$util$HashMap$Node_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $de$mirkosertic$bytecoder$classlib$BytecoderCharsetDecoder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $malformedInputAction (ref $java$lang$Object)) (field $unmappableCharacterAction (ref $java$lang$Object)) (field $maxCharsPerByte f32) (field $state i32) (field $replacement (ref $java$lang$Object)) (field $charset (ref $java$lang$Object)) (field $averageCharsPerByte f32) $java$nio$charset$CharsetDecoder))
    (type $de$mirkosertic$bytecoder$classlib$BytecoderCharsetDecoder_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$Hashtable (struct_subtype (field $runtimetype (ref $runtimetype)) (field $modCount i32) $java$util$Dictionary))
    (type $java$util$Hashtable_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$AbstractMap (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$util$AbstractMap_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $org$junit$rules$ExternalResource (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $org$junit$rules$ExternalResource_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$Exception (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$Throwable))
    (type $java$lang$Exception_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $de$mirkosertic$bytecoder$classlib$BytecoderCharsetEncoder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $malformedInputAction (ref $java$lang$Object)) (field $unmappableCharacterAction (ref $java$lang$Object)) (field $state i32) (field $cachedDecoder (ref $java$lang$Object)) (field $charset (ref $java$lang$Object)) (field $averageBytesPerChar f32) (field $maxBytesPerChar f32) $java$nio$charset$CharsetEncoder))
    (type $de$mirkosertic$bytecoder$classlib$BytecoderCharsetEncoder_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$nio$charset$CoderMalfunctionError (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$Error))
    (type $java$nio$charset$CoderMalfunctionError_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$Set_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$RuntimeException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$Exception))
    (type $java$lang$RuntimeException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$Float (struct_subtype (field $runtimetype (ref $runtimetype)) (field $value f32) $java$lang$Number))
    (type $java$lang$Float_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $TYPE (ref $java$lang$Object)) $runtimetype))
    (type $java$util$LinkedHashMap$Entry (struct_subtype (field $runtimetype (ref $runtimetype)) (field $next (ref $java$lang$Object)) (field $hash i32) (field $key (ref $java$lang$Object)) (field $value (ref $java$lang$Object)) $java$util$HashMap$Node))
    (type $java$util$LinkedHashMap$Entry_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$HashMap (struct_subtype (field $runtimetype (ref $runtimetype)) (field $loadFactor f32) (field $threshold i32) (field $size i32) (field $modCount i32) $java$util$AbstractMap))
    (type $java$util$HashMap_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$List_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$nio$HeapByteBuffer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $mark i32) (field $position i32) (field $capacity i32) (field $segment (ref $java$lang$Object)) (field $limit i32) (field $address i64) (field $offset i32) $java$nio$ByteBuffer))
    (type $java$nio$HeapByteBuffer_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $ARRAY_BASE_OFFSET i64) (field $ARRAY_INDEX_SCALE i64) $runtimetype))
    (type $java$util$ImmutableCollections$AbstractImmutableMap (struct_subtype (field $runtimetype (ref $runtimetype)) $java$util$AbstractMap))
    (type $java$util$ImmutableCollections$AbstractImmutableMap_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$Long (struct_subtype (field $runtimetype (ref $runtimetype)) (field $value i64) $java$lang$Number))
    (type $java$lang$Long_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $TYPE (ref $java$lang$Object)) $runtimetype))
    (type $java$io$Writer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $lock (ref $java$lang$Object)) $java$lang$Object))
    (type $java$io$Writer_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$Integer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $value i32) $java$lang$Number))
    (type $java$lang$Integer_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $TYPE (ref $java$lang$Object)) $runtimetype))
    (type $java$io$OutputStream (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$io$OutputStream_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $org$junit$rules$TemporaryFolder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $parentFolder (ref $java$lang$Object)) $org$junit$rules$ExternalResource))
    (type $org$junit$rules$TemporaryFolder_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$AbstractCollection (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$util$AbstractCollection_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$io$InputStream (struct_subtype (field $runtimetype (ref $runtimetype)) $java$lang$Object))
    (type $java$io$InputStream_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$Properties (struct_subtype (field $runtimetype (ref $runtimetype)) (field $modCount i32) (field $map (ref $java$lang$Object)) (field $defaults (ref $java$lang$Object)) $java$util$Hashtable))
    (type $java$util$Properties_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $UNSAFE (ref $java$lang$Object)) $runtimetype))
    (type $java$lang$AssertionError (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$Error))
    (type $java$lang$AssertionError_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$Byte (struct_subtype (field $runtimetype (ref $runtimetype)) (field $value i32) $java$lang$Number))
    (type $java$lang$Byte_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $TYPE (ref $java$lang$Object)) $runtimetype))
    (type $jdk$internal$misc$ScopedMemoryAccess$Scope$ScopedAccessError (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$Error))
    (type $jdk$internal$misc$ScopedMemoryAccess$Scope$ScopedAccessError_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $INSTANCE (ref $java$lang$Object)) $runtimetype))
    (type $java$util$concurrent$ConcurrentHashMap (struct_subtype (field $runtimetype (ref $runtimetype)) (field $delegate (ref $java$lang$Object)) $java$util$AbstractMap))
    (type $java$util$concurrent$ConcurrentHashMap_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $de$mirkosertic$bytecoder$classlib$BytecoderCharset (struct_subtype (field $runtimetype (ref $runtimetype)) (field $canonicalName (ref $java$lang$Object)) $java$nio$charset$Charset))
    (type $de$mirkosertic$bytecoder$classlib$BytecoderCharset_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$nio$HeapCharBuffer (struct_subtype (field $runtimetype (ref $runtimetype)) (field $mark i32) (field $position i32) (field $capacity i32) (field $segment (ref $java$lang$Object)) (field $limit i32) (field $address i64) (field $offset i32) $java$nio$CharBuffer))
    (type $java$nio$HeapCharBuffer_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $ARRAY_BASE_OFFSET i64) (field $ARRAY_INDEX_SCALE i64) $runtimetype))
    (type $java$lang$VirtualMachineError (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$Error))
    (type $java$lang$VirtualMachineError_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$HashMap$TreeNode (struct_subtype (field $runtimetype (ref $runtimetype)) (field $next (ref $java$lang$Object)) (field $hash i32) (field $key (ref $java$lang$Object)) (field $value (ref $java$lang$Object)) (field $prev (ref $java$lang$Object)) (field $right (ref $java$lang$Object)) (field $left (ref $java$lang$Object)) (field $parent (ref $java$lang$Object)) $java$util$LinkedHashMap$Entry))
    (type $java$util$HashMap$TreeNode_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$IllegalStateException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$lang$IllegalStateException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$InternalError (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$VirtualMachineError))
    (type $java$lang$InternalError_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$UnsupportedOperationException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$lang$UnsupportedOperationException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$io$FilterOutputStream (struct_subtype (field $runtimetype (ref $runtimetype)) (field $closeLock (ref $java$lang$Object)) (field $out (ref $java$lang$Object)) $java$io$OutputStream))
    (type $java$io$FilterOutputStream_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$io$BufferedWriter (struct_subtype (field $runtimetype (ref $runtimetype)) (field $lock (ref $java$lang$Object)) (field $out (ref $java$lang$Object)) (field $nChars i32) (field $nextChar i32) $java$io$Writer))
    (type $java$io$BufferedWriter_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) (field $defaultCharBufferSize i32) $runtimetype))
    (type $java$lang$IndexOutOfBoundsException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$lang$IndexOutOfBoundsException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$IllegalArgumentException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$lang$IllegalArgumentException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$nio$BufferUnderflowException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$nio$BufferUnderflowException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$ImmutableCollections$AbstractImmutableCollection (struct_subtype (field $runtimetype (ref $runtimetype)) $java$util$AbstractCollection))
    (type $java$util$ImmutableCollections$AbstractImmutableCollection_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $sun$nio$cs$StreamEncoder (struct_subtype (field $runtimetype (ref $runtimetype)) (field $lock (ref $java$lang$Object)) (field $lcb (ref $java$lang$Object)) (field $out (ref $java$lang$Object)) (field $ch (ref $java$lang$Object)) (field $cs (ref $java$lang$Object)) (field $encoder (ref $java$lang$Object)) (field $bb (ref $java$lang$Object)) $java$io$Writer))
    (type $sun$nio$cs$StreamEncoder_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$ConcurrentModificationException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$util$ConcurrentModificationException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$io$OutputStreamWriter (struct_subtype (field $runtimetype (ref $runtimetype)) (field $lock (ref $java$lang$Object)) (field $se (ref $java$lang$Object)) $java$io$Writer))
    (type $java$io$OutputStreamWriter_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$ImmutableCollections$MapN (struct_subtype (field $runtimetype (ref $runtimetype)) (field $size i32) $java$util$ImmutableCollections$AbstractImmutableMap))
    (type $java$util$ImmutableCollections$MapN_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$NullPointerException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$lang$NullPointerException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$nio$BufferOverflowException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$RuntimeException))
    (type $java$nio$BufferOverflowException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$io$FileInputStream (struct_subtype (field $runtimetype (ref $runtimetype)) (field $fd (ref $java$lang$Object)) (field $path (ref $java$lang$Object)) $java$io$InputStream))
    (type $java$io$FileInputStream_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$io$FileOutputStream (struct_subtype (field $runtimetype (ref $runtimetype)) (field $fd (ref $java$lang$Object)) (field $path (ref $java$lang$Object)) $java$io$OutputStream))
    (type $java$io$FileOutputStream_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$io$PrintStream (struct_subtype (field $runtimetype (ref $runtimetype)) (field $closeLock (ref $java$lang$Object)) (field $out (ref $java$lang$Object)) (field $charOut (ref $java$lang$Object)) (field $textOut (ref $java$lang$Object)) $java$io$FilterOutputStream))
    (type $java$io$PrintStream_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$ImmutableCollections$AbstractImmutableList (struct_subtype (field $runtimetype (ref $runtimetype)) $java$util$ImmutableCollections$AbstractImmutableCollection))
    (type $java$util$ImmutableCollections$AbstractImmutableList_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$lang$StringIndexOutOfBoundsException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$IndexOutOfBoundsException))
    (type $java$lang$StringIndexOutOfBoundsException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$ImmutableCollections$AbstractImmutableSet (struct_subtype (field $runtimetype (ref $runtimetype)) $java$util$ImmutableCollections$AbstractImmutableCollection))
    (type $java$util$ImmutableCollections$AbstractImmutableSet_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$nio$ReadOnlyBufferException (struct_subtype (field $runtimetype (ref $runtimetype)) (field $message (ref $java$lang$Object)) (field $cause (ref $java$lang$Object)) $java$lang$UnsupportedOperationException))
    (type $java$nio$ReadOnlyBufferException_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$ImmutableCollections$SetN (struct_subtype (field $runtimetype (ref $runtimetype)) (field $size i32) $java$util$ImmutableCollections$AbstractImmutableSet))
    (type $java$util$ImmutableCollections$SetN_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$ImmutableCollections$List12 (struct_subtype (field $runtimetype (ref $runtimetype)) (field $e0 (ref $java$lang$Object)) (field $e1 (ref $java$lang$Object)) $java$util$ImmutableCollections$AbstractImmutableList))
    (type $java$util$ImmutableCollections$List12_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    (type $java$util$ImmutableCollections$ListN (struct_subtype (field $runtimetype (ref $runtimetype)) $java$util$ImmutableCollections$AbstractImmutableList))
    (type $java$util$ImmutableCollections$ListN_rtt (struct_subtype (field $typeId i32) (field $impTypes (ref $t1)) (field $lambdaMethod i32) (field $vt_resolver (ref $t0)) $runtimetype))
    )
